[project]
name = "gearbotCLI"
version = "1.0.0"
dependencies = [
    "playwright"
]
requires-python = ">=3.13"
authors = [{name = "Christian Martinez"}]
description = "Automated search for music gear"
readme = "README.md"
