[project]
name = "gearbotCLI"
version = "0.0"
dependencies = [
    "playwright",
    "pylint",
    "typer",
]
requires-python = ">=3.8"
authors = [{name = "Christian Martinez"}]
description = "Automated search for music gear"
readme = "README.md"

[project.scripts]
gearbot = "cli:app"
